name: Integration

on:
  push:
    branches:
    - '**'
    - '!master'
  pull_request:
    branches:
    - '**'
    - '!master'

env:
  PYTHONPATH: src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Unit Test
      run: |
        coverage run --source=src --branch -m pytest
        coverage html
    - name: Mutation Test
      run: mutmut -s run
      continue-on-error: true
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: Coverage
        path: htmlcov